# Generated by Django 5.0.1 on 2024-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clients_image", models.ImageField(upload_to="clients_image/")),
                (
                    "clients_name",
                    models.CharField(default="@Tachsol Consult LTD", max_length=500),
                ),
                ("location", models.CharField(default="Accra", max_length=50)),
                ("description", models.CharField(default="Tachsol", max_length=100)),
                ("client_contact", models.IntegerField(default=233208157526)),
                ("url_link", models.URLField(default="http://tachsol.com")),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="portfolio_images/")),
                ("title", models.CharField(default="Mr", max_length=100)),
                ("name", models.CharField(default="Tachsol", max_length=50)),
                ("position", models.CharField(blank=True, default="", max_length=50)),
                (
                    "email",
                    models.EmailField(default="tachsol.km@gmail.com", max_length=254),
                ),
                (
                    "content",
                    models.TextField(default="Tachsol Consult", max_length=1500),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Tachsol", max_length=100)),
                ("updated_by", models.CharField(default="Mr. Offei", max_length=50)),
                (
                    "service_image",
                    models.ImageField(
                        default="static/images/service/default_image.png",
                        upload_to="Service_images/",
                    ),
                ),
                (
                    "content",
                    models.TextField(default="Enter the text here", max_length=1500),
                ),
                (
                    "description",
                    models.CharField(default="We serve you better", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("name", models.CharField(default="Tachsol", max_length=100)),
                ("position", models.CharField(default="Founder", max_length=50)),
                ("contact", models.IntegerField(default=233208157526)),
            ],
        ),
    ]
