# Generated by Django 5.0.1 on 2024-02-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="title",
            field=models.CharField(
                choices=[("Mr.", "Mr"), ("Ms.", "Ms"), ("Mrs.", "Mrs")], max_length=5
            ),
        ),
    ]
