# Generated by Django 5.0.1 on 2024-02-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scopeofopearation",
            name="description",
        ),
        migrations.AlterField(
            model_name="services",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="mainapp.scopeofopearation",
            ),
        ),
    ]
