# Generated by Django 5.0.1 on 2024-02-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_remove_scopeofopearation_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("content", models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name="title",
            name="gender",
            field=models.CharField(
                choices=[("Mr.", "Mr"), ("Ms.", "Ms"), ("Mrs.", "Mrs")],
                default="Mr",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(
                choices=[("Mr.", "Mr"), ("Ms.", "Ms"), ("Mrs.", "Mrs")], max_length=5
            ),
        ),
    ]
