# Generated by Django 4.1 on 2023-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="Client_image",
            field=models.ImageField(upload_to="client_images/"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="Client_name",
            field=models.CharField(max_length=500),
        ),
    ]
