# Generated by Django 4.1 on 2023-10-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_alter_clients_client_image_alter_clients_client_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="Client_image",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="Client_name",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="year_joined",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="staff_portfolio",
        ),
        migrations.AddField(
            model_name="clients",
            name="Clients_image",
            field=models.ImageField(blank=True, upload_to="clients_image/"),
        ),
        migrations.AddField(
            model_name="clients",
            name="Clients_name",
            field=models.CharField(default="@Tachsol Consult LTD", max_length=500),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="Name",
            field=models.CharField(default="Tachsol", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="content",
            field=models.TextField(default="Tachsol Consult", max_length=1500),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(blank=True, upload_to="portfolio_images/"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="position",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title",
            field=models.CharField(default="Mr", max_length=100),
        ),
        migrations.DeleteModel(
            name="IndividualAbooutPage",
        ),
    ]
