# Generated by Django 4.1 on 2023-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_remove_clients_client_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Tachsol", max_length=100)),
                ("position", models.CharField(default="Founder", max_length=50)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
