# Generated by Django 4.1 on 2023-12-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0008_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_the_about_page", models.TextField(max_length=2000)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="clients",
            old_name="Clients_image",
            new_name="clients_image",
        ),
        migrations.RenameField(
            model_name="clients",
            old_name="Clients_name",
            new_name="clients_name",
        ),
        migrations.AddField(
            model_name="clients",
            name="description",
            field=models.CharField(default="Tachsol", max_length=100),
        ),
        migrations.AddField(
            model_name="clients",
            name="location",
            field=models.CharField(default="Accra", max_length=50),
        ),
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.CharField(default="We serve you better", max_length=100),
        ),
        migrations.AddField(
            model_name="teammembers",
            name="contact",
            field=models.IntegerField(default=" "),
        ),
        migrations.AddField(
            model_name="teammembers",
            name="meeting_hours",
            field=models.DateTimeField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="content",
            field=models.TextField(default="Enter the text here", max_length=1500),
        ),
    ]
