# Generated by Django 4.1 on 2024-01-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0009_about_rename_clients_image_clients_clients_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="update_the_about_page",
            new_name="about_content",
        ),
        migrations.RemoveField(
            model_name="about",
            name="location",
        ),
        migrations.AddField(
            model_name="about",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="clients",
            name="ulr_link",
            field=models.URLField(default="tachsol.com"),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact",
            field=models.CharField(blank=True, default=233207758838, max_length=10),
        ),
        migrations.AddField(
            model_name="services",
            name="service_image",
            field=models.ImageField(
                default="static/images/service/default_image.png",
                upload_to="Service_images/",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="service_name",
            field=models.CharField(default="Disput Resolution", max_length=100),
        ),
        migrations.AlterField(
            model_name="clients",
            name="clients_image",
            field=models.ImageField(upload_to="clients_image/"),
        ),
        migrations.AlterField(
            model_name="teammembers",
            name="contact",
            field=models.CharField(default=233207758838, max_length=10),
        ),
    ]
