# Generated by Django 4.1 on 2024-01-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0011_alter_contact_contact_alter_teammembers_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammembers",
            name="contact",
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.IntegerField(blank=True, default=233207758838),
        ),
    ]
