# Generated by Django 4.1 on 2024-01-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0013_alter_contact_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.FloatField(),
        ),
    ]
