# Generated by Django 4.1 on 2024-01-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0015_remove_contact_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=models.FloatField(default=233207758838),
        ),
    ]
