# Generated by Django 4.1 on 2024-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0016_contact_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="service_name",
        ),
        migrations.RemoveField(
            model_name="teammembers",
            name="meeting_hours",
        ),
        migrations.AddField(
            model_name="services",
            name="name",
            field=models.CharField(default="Tachsol", max_length=100),
        ),
    ]
