# Generated by Django 4.1 on 2024-01-03 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0017_remove_services_service_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
