# Generated by Django 4.1 on 2024-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0019_clients_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="contact",
            field=models.BigIntegerField(default=233208157526),
        ),
    ]
